
 - name: enable EPEL repository
   yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: installed

 - name: install os dependencies
   yum:
    name: gcc,openssl-devel,libffi-devel,python-devel,openssl-devel,libcurl,libcurl-devel
    state: installed