
 - name: install python dependencies
   yum:
    name: python-pip, python-wheel
    state: installed
   when: not notebook.use_anaconda

 - name: install python packages
   shell: |
    pip install --upgrade pip
    pip install --upgrade ipykernel
   when: not notebook.use_anaconda

 - name: update python packages
   shell: |
    pip install --upgrade paramiko