
 - name: remove old python yarn cluster kernel launcher
   file:
     path: "{{ jupyter_kernelspec_location }}/spark_python_yarn_cluster"
     state: absent

 - name: remove old python yarn client kernel launcher
   file:
     path: "{{ jupyter_kernelspec_location }}/spark_python_yarn_client"
     state: absent

 - name: create placeholder for python yarn cluster kernel launcher
   file:
    path: "{{ jupyter_kernelspec_location }}/spark_python_yarn_cluster"
    state: directory
    owner: "{{ notebook.user }}"
    group: "{{ notebook.user }}"

 - name: create placeholder for python yarn client kernel launcher
   file:
    path: "{{ jupyter_kernelspec_location }}/spark_python_yarn_client"
    state: directory
    owner: "{{ notebook.user }}"
    group: "{{ notebook.user }}"

 - name: update python kernel cluster launcher
   shell: "tar -zxvf {{ install_temp_dir }}/{{ notebook.elyra_kernelspec_package_name }} --strip 1 --directory {{ jupyter_kernelspec_location }}/spark_python_yarn_cluster spark_python_yarn_cluster"
   ignore_errors: yes

 - name: update python kernel client launcher
   shell: "tar -zxvf {{ install_temp_dir }}/{{ notebook.elyra_kernelspec_package_name }} --strip 1 --directory {{ jupyter_kernelspec_location }}/spark_python_yarn_client spark_python_yarn_client"
   ignore_errors: yes

 - name: disable impersonation based on configuration (only applies to cluster mode)
   shell: " sed -i 's/ --proxy-user ${KERNEL_USERNAME:-ERROR__NO__KERNEL_USERNAME}//g' {{ jupyter_kernelspec_location }}/spark_python_yarn_cluster/kernel.json"
   ignore_errors: yes
   when: (notebook.enable_impersonation == false)

