
#- name: anaconda
#  hosts: all
#  vars:
#    anaconda:
#      python_version: 2
#      update_path: false
#  remote_user: root
#  roles:
#   - role: anaconda

- name: notebook platform dependencies
  hosts: all
  vars:
    notebook:
      use_anaconda: true
  remote_user: root
  roles:
    - role: notebook
