- name: ambari setup
  hosts: all
  vars:
    ambari:
      enable_kerberos: true
  remote_user: root
  roles:
    - role: common
    - role: ambari

- name: anaconda
  hosts: all
  vars:
    anaconda:
      update_path: true
  remote_user: root
  roles:
   - role: anaconda

- name: notebook platform dependencies
  hosts: all
  vars:
    notebook:
      use_anaconda: true
  remote_user: root
  roles:
    - role: notebook
