- name: install common dependencies
  hosts: all
  vars:
     install_java: false
  remote_user: root
  roles:
    - role: common

- name: ambari setup
  hosts: all
  remote_user: root
  roles:
    - role: iop

- name: anaconda
  hosts: all
  vars:
    anaconda:
      python_version: 2
      update_path: false
  remote_user: root
  roles:
   - role: anaconda

- name: notebook platform dependencies
  hosts: all
  remote_user: root
  roles:
    - role: notebook
