
- name: create bin directory for utility scripts
  file:
    path: "{{ install_dir }}/bin"
    state: directory
  when: inventory_hostname in groups['master']

- name: create do.sh utility.
  template:
    src: do.sh.j2
    dest: "{{ install_dir }}/bin/do.sh"
    mode: 0744
  when: inventory_hostname in groups['master']
