# Account name of remote user. Ansible will use this user account to ssh into
# the managed machines. The user must be able to use sudo without asking
# for password.
ansible_connection: ssh
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/dev_key.pem

gather_facts: True
gathering: smart

# Tell ansible not to check host key
host_key_checking: False

# Installation folders
install_temp_dir: /tmp/ansible-install
install_dir: /opt/install

# Common packages
install_java: False
python_version: 2

security:
  enable_kerberos: False
