kafka:
  version: 0.11.0.1
  data_dir: /var/kafka
  # https://archive.apache.org/dist/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz
  download_location: https://archive.apache.org/dist/kafka
  user: "kafka"       # the name of the (OS)user created for spark
  user_groups: []             # Optional list of (OS)groups the new spark user should belong to
  user_shell: "/bin/false"    # the elasticsearch user's default shell
